### ISSUE TITLE
web-based admin

### ISSUE THREAD

**Issue by computersalat** [karesansui/pysilhouette#4]
README is telling:
"Comes with an easy web-based administration interface."

Where is it ? How can I access it?

**Comment by taizo** [comment]
Sorry, but we cannot translate Japanese into English correctly.
It truly means "it is mainly used for web application to execute background tasks." 

As of this writing a web-based administration UI is not implemented.

**Comment by computersalat** [comment]
Ok, thanks.
I will fix README and create a merge request.

Cheers
  Chris

Am 31.07.2012 04:43, schrieb Taizo Ito:

> Sorry, but we cannot translate Japanese into English correctly.
> It truly means "it is mainly used for web application to execute background tasks."
> 
> As of this writing a web-based administration UI is not implemented.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/karesansui/pysilhouette/issues/4#issuecomment-7388353

## 

## Christian

```
- Please do not 'CC' me on list mails.
       Just reply to the list :)
```

---

Der ultimative shop für Sportbekleidung und Zubehör

## http://www.sc24.de
